import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "de" | "fr" | "es" | "nl" | "hi" | "te" | "zh" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.courses": "Courses",
    "nav.programs": "Programs",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.apply": "Apply Now",
    "nav.academics": "Academics",
    "nav.tracks": "Tracks",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "Threat Intel",
    "nav.resources": "Resources",
    "hero.title": "Sovereign Cybersecurity Education",
    "hero.subtitle": "Train on production-grade infrastructure with world-class faculty",
    "hero.cta": "Get Started",
    "resources.title": "Resources",
    "resources.subtitle": "Download our comprehensive guides and research papers",
    "resources.ebooks": "eBooks",
    "resources.whitepapers": "Whitepapers",
    "resources.download": "Download",
    "resources.login_required": "Login Required",
    "resources.kyc_required": "KYC Required",
    "resources.locked": "Unlock Access",
    "resources.badge": "Knowledge Hub",
    "resources.all": "All Resources",
    "resources.premium_title": "Unlock Premium Resources",
    "resources.premium_desc": "Create a free account to access our comprehensive ebooks and whitepapers.",
    "resources.premium_some_kyc": "Premium resources requiring account registration. Some resources require KYC verification.",
    "resources.pages": "pages",
    "resources.tcpwave_docs": "TCPWave Documentation",
    "resources.tcpwave_docs_desc": "Complete documentation for TCPWave DDI platform including API reference, deployment guides, and best practices.",
    "resources.view_docs": "View Documentation",
    "resources.access": "Access",
    "resources.cat_ebooks": "eBooks",
    "resources.cat_ebooks_desc": "Comprehensive guides on cybersecurity topics, career development, and certifications.",
    "resources.cat_whitepapers": "Whitepapers",
    "resources.cat_whitepapers_desc": "In-depth technical papers on DNS security, DDI, and enterprise architecture.",
    "resources.cat_cheatsheets": "Cheat Sheets",
    "resources.cat_cheatsheets_desc": "Quick reference guides for security tools, commands, and best practices.",
    "resources.cat_tools": "Tools",
    "resources.cat_tools_desc": "Open-source security tools developed by T-SPAN and recommended by our faculty.",
    "resources.cat_glossary": "Glossary",
    "resources.cat_glossary_desc": "Comprehensive dictionary of cybersecurity terms and acronyms.",
    "resources.cat_dns_guide": "DNS Security Guide",
    "resources.cat_dns_guide_desc": "The ultimate guide to enterprise DNS security and threat protection.",
    "common.loading": "Loading...",
    "common.learn_more": "Learn More",
    "common.view_all": "View All",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "footer.copyright": "All rights reserved",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },
  de: {
    "nav.home": "Startseite",
    "nav.courses": "Kurse",
    "nav.programs": "Programme",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "nav.login": "Anmelden",
    "nav.apply": "Jetzt bewerben",
    "nav.academics": "Akademisch",
    "nav.tracks": "Tracks",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "Bedrohungsanalyse",
    "nav.resources": "Ressourcen",
    "hero.title": "Souveräne Cybersicherheitsausbildung",
    "hero.subtitle": "Trainieren Sie auf produktionsreifer Infrastruktur mit erstklassigen Dozenten",
    "hero.cta": "Loslegen",
    "resources.title": "Ressourcen",
    "resources.subtitle": "Laden Sie unsere umfassenden Leitfäden und Forschungsarbeiten herunter",
    "resources.ebooks": "E-Books",
    "resources.whitepapers": "Whitepapers",
    "resources.download": "Herunterladen",
    "resources.login_required": "Anmeldung erforderlich",
    "resources.kyc_required": "KYC erforderlich",
    "resources.locked": "Zugang freischalten",
    "resources.badge": "Wissenszentrum",
    "resources.all": "Alle Ressourcen",
    "resources.premium_title": "Premium-Ressourcen freischalten",
    "resources.premium_desc": "Erstellen Sie ein kostenloses Konto, um auf unsere umfassenden E-Books und Whitepapers zuzugreifen.",
    "resources.premium_some_kyc": "Premium-Ressourcen erfordern eine Kontoregistrierung. Einige Ressourcen erfordern eine KYC-Verifizierung.",
    "resources.pages": "Seiten",
    "resources.tcpwave_docs": "TCPWave Dokumentation",
    "resources.tcpwave_docs_desc": "Vollständige Dokumentation für TCPWave DDI-Plattform einschließlich API-Referenz, Bereitstellungshandbücher und Best Practices.",
    "resources.view_docs": "Dokumentation anzeigen",
    "resources.access": "Zugriff",
    "resources.cat_ebooks": "E-Books",
    "resources.cat_ebooks_desc": "Umfassende Leitfäden zu Cybersicherheitsthemen, Karriereentwicklung und Zertifizierungen.",
    "resources.cat_whitepapers": "Whitepapers",
    "resources.cat_whitepapers_desc": "Detaillierte technische Papiere zu DNS-Sicherheit, DDI und Unternehmensarchitektur.",
    "resources.cat_cheatsheets": "Spickzettel",
    "resources.cat_cheatsheets_desc": "Schnelle Referenzanleitungen für Sicherheitstools, Befehle und Best Practices.",
    "resources.cat_tools": "Werkzeuge",
    "resources.cat_tools_desc": "Open-Source-Sicherheitstools, entwickelt von T-SPAN und empfohlen von unseren Dozenten.",
    "resources.cat_glossary": "Glossar",
    "resources.cat_glossary_desc": "Umfassendes Wörterbuch für Cybersicherheitsbegriffe und Abkürzungen.",
    "resources.cat_dns_guide": "DNS-Sicherheitshandbuch",
    "resources.cat_dns_guide_desc": "Der ultimative Leitfaden für Unternehmens-DNS-Sicherheit und Bedrohungsschutz.",
    "common.loading": "Laden...",
    "common.learn_more": "Mehr erfahren",
    "common.view_all": "Alle anzeigen",
    "common.submit": "Absenden",
    "common.cancel": "Abbrechen",
    "footer.copyright": "Alle Rechte vorbehalten",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.courses": "Cours",
    "nav.programs": "Programmes",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.login": "Connexion",
    "nav.apply": "Postuler",
    "nav.academics": "Académique",
    "nav.tracks": "Parcours",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "Renseignements",
    "nav.resources": "Ressources",
    "hero.title": "Éducation Souveraine en Cybersécurité",
    "hero.subtitle": "Formez-vous sur une infrastructure de production avec des enseignants de classe mondiale",
    "hero.cta": "Commencer",
    "resources.title": "Ressources",
    "resources.subtitle": "Téléchargez nos guides complets et documents de recherche",
    "resources.ebooks": "Livres numériques",
    "resources.whitepapers": "Livres blancs",
    "resources.download": "Télécharger",
    "resources.login_required": "Connexion requise",
    "resources.kyc_required": "KYC requise",
    "resources.locked": "Débloquer l'accès",
    "resources.badge": "Centre de connaissances",
    "resources.all": "Toutes les ressources",
    "resources.premium_title": "Débloquez les ressources premium",
    "resources.premium_desc": "Créez un compte gratuit pour accéder à nos guides complets et livres blancs.",
    "resources.premium_some_kyc": "Ressources premium nécessitant une inscription. Certaines ressources nécessitent une vérification KYC.",
    "resources.pages": "pages",
    "resources.tcpwave_docs": "Documentation TCPWave",
    "resources.tcpwave_docs_desc": "Documentation complète pour la plateforme DDI TCPWave comprenant la référence API, les guides de déploiement et les meilleures pratiques.",
    "resources.view_docs": "Voir la documentation",
    "resources.access": "Accès",
    "resources.cat_ebooks": "Livres numériques",
    "resources.cat_ebooks_desc": "Guides complets sur la cybersécurité, le développement de carrière et les certifications.",
    "resources.cat_whitepapers": "Livres blancs",
    "resources.cat_whitepapers_desc": "Documents techniques approfondis sur la sécurité DNS, DDI et l'architecture d'entreprise.",
    "resources.cat_cheatsheets": "Aide-mémoire",
    "resources.cat_cheatsheets_desc": "Guides de référence rapide pour les outils de sécurité, commandes et meilleures pratiques.",
    "resources.cat_tools": "Outils",
    "resources.cat_tools_desc": "Outils de sécurité open source développés par T-SPAN et recommandés par nos professeurs.",
    "resources.cat_glossary": "Glossaire",
    "resources.cat_glossary_desc": "Dictionnaire complet des termes et acronymes de cybersécurité.",
    "resources.cat_dns_guide": "Guide de sécurité DNS",
    "resources.cat_dns_guide_desc": "Le guide ultime de la sécurité DNS d'entreprise et de la protection contre les menaces.",
    "common.loading": "Chargement...",
    "common.learn_more": "En savoir plus",
    "common.view_all": "Voir tout",
    "common.submit": "Soumettre",
    "common.cancel": "Annuler",
    "footer.copyright": "Tous droits réservés",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
  },
  es: {
    "nav.home": "Inicio",
    "nav.courses": "Cursos",
    "nav.programs": "Programas",
    "nav.about": "Acerca de",
    "nav.contact": "Contacto",
    "nav.login": "Iniciar sesión",
    "nav.apply": "Aplicar ahora",
    "nav.academics": "Académico",
    "nav.tracks": "Pistas",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "Inteligencia",
    "nav.resources": "Recursos",
    "hero.title": "Educación Soberana en Ciberseguridad",
    "hero.subtitle": "Entrene en infraestructura de producción con profesores de clase mundial",
    "hero.cta": "Empezar",
    "resources.title": "Recursos",
    "resources.subtitle": "Descargue nuestras guías completas y documentos de investigación",
    "resources.ebooks": "Libros electrónicos",
    "resources.whitepapers": "Documentos técnicos",
    "resources.download": "Descargar",
    "resources.login_required": "Inicio de sesión requerido",
    "resources.kyc_required": "KYC requerido",
    "resources.locked": "Desbloquear acceso",
    "resources.badge": "Centro de conocimiento",
    "resources.all": "Todos los recursos",
    "resources.premium_title": "Desbloquear recursos premium",
    "resources.premium_desc": "Cree una cuenta gratuita para acceder a nuestras guías completas y documentos técnicos.",
    "resources.premium_some_kyc": "Recursos premium que requieren registro de cuenta. Algunos recursos requieren verificación KYC.",
    "resources.pages": "páginas",
    "resources.tcpwave_docs": "Documentación TCPWave",
    "resources.tcpwave_docs_desc": "Documentación completa para la plataforma DDI de TCPWave que incluye referencia de API, guías de implementación y mejores prácticas.",
    "resources.view_docs": "Ver documentación",
    "resources.access": "Acceso",
    "resources.cat_ebooks": "Libros electrónicos",
    "resources.cat_ebooks_desc": "Guías completas sobre temas de ciberseguridad, desarrollo profesional y certificaciones.",
    "resources.cat_whitepapers": "Documentos técnicos",
    "resources.cat_whitepapers_desc": "Documentos técnicos detallados sobre seguridad DNS, DDI y arquitectura empresarial.",
    "resources.cat_cheatsheets": "Hojas de referencia",
    "resources.cat_cheatsheets_desc": "Guías de referencia rápida para herramientas de seguridad, comandos y mejores prácticas.",
    "resources.cat_tools": "Herramientas",
    "resources.cat_tools_desc": "Herramientas de seguridad de código abierto desarrolladas por T-SPAN y recomendadas por nuestros profesores.",
    "resources.cat_glossary": "Glosario",
    "resources.cat_glossary_desc": "Diccionario completo de términos y acrónimos de ciberseguridad.",
    "resources.cat_dns_guide": "Guía de seguridad DNS",
    "resources.cat_dns_guide_desc": "La guía definitiva para la seguridad DNS empresarial y protección contra amenazas.",
    "common.loading": "Cargando...",
    "common.learn_more": "Saber más",
    "common.view_all": "Ver todo",
    "common.submit": "Enviar",
    "common.cancel": "Cancelar",
    "footer.copyright": "Todos los derechos reservados",
    "footer.privacy": "Política de privacidad",
    "footer.terms": "Términos de servicio",
  },
  nl: {
    "nav.home": "Home",
    "nav.courses": "Cursussen",
    "nav.programs": "Programma's",
    "nav.about": "Over ons",
    "nav.contact": "Contact",
    "nav.login": "Inloggen",
    "nav.apply": "Nu aanmelden",
    "nav.academics": "Academisch",
    "nav.tracks": "Tracks",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "Dreigingsinformatie",
    "nav.resources": "Bronnen",
    "hero.title": "Soevereine Cybersecurity Opleiding",
    "hero.subtitle": "Train op productie-infrastructuur met docenten van wereldklasse",
    "hero.cta": "Aan de slag",
    "resources.title": "Bronnen",
    "resources.subtitle": "Download onze uitgebreide gidsen en onderzoeksdocumenten",
    "resources.ebooks": "E-books",
    "resources.whitepapers": "Whitepapers",
    "resources.download": "Downloaden",
    "resources.login_required": "Inloggen vereist",
    "resources.kyc_required": "KYC vereist",
    "resources.locked": "Toegang ontgrendelen",
    "resources.badge": "Kenniscentrum",
    "resources.all": "Alle bronnen",
    "resources.premium_title": "Premium bronnen ontgrendelen",
    "resources.premium_desc": "Maak een gratis account aan om toegang te krijgen tot onze uitgebreide gidsen en whitepapers.",
    "resources.premium_some_kyc": "Premium bronnen die accountregistratie vereisen. Sommige bronnen vereisen KYC-verificatie.",
    "resources.pages": "pagina's",
    "resources.tcpwave_docs": "TCPWave Documentatie",
    "resources.tcpwave_docs_desc": "Volledige documentatie voor TCPWave DDI-platform inclusief API-referentie, implementatiegidsen en best practices.",
    "resources.view_docs": "Bekijk documentatie",
    "resources.access": "Toegang",
    "resources.cat_ebooks": "E-books",
    "resources.cat_ebooks_desc": "Uitgebreide gidsen over cybersecurity-onderwerpen, carrièreontwikkeling en certificeringen.",
    "resources.cat_whitepapers": "Whitepapers",
    "resources.cat_whitepapers_desc": "Diepgaande technische documenten over DNS-beveiliging, DDI en bedrijfsarchitectuur.",
    "resources.cat_cheatsheets": "Spiekbriefjes",
    "resources.cat_cheatsheets_desc": "Snelle naslaggidsen voor beveiligingstools, commando's en best practices.",
    "resources.cat_tools": "Hulpmiddelen",
    "resources.cat_tools_desc": "Open-source beveiligingstools ontwikkeld door T-SPAN en aanbevolen door onze docenten.",
    "resources.cat_glossary": "Woordenlijst",
    "resources.cat_glossary_desc": "Uitgebreid woordenboek van cybersecurity-termen en acroniemen.",
    "resources.cat_dns_guide": "DNS-beveiligingsgids",
    "resources.cat_dns_guide_desc": "De ultieme gids voor bedrijfs-DNS-beveiliging en bescherming tegen bedreigingen.",
    "common.loading": "Laden...",
    "common.learn_more": "Meer informatie",
    "common.view_all": "Alles bekijken",
    "common.submit": "Verzenden",
    "common.cancel": "Annuleren",
    "footer.copyright": "Alle rechten voorbehouden",
    "footer.privacy": "Privacybeleid",
    "footer.terms": "Servicevoorwaarden",
  },
  hi: {
    "nav.home": "होम",
    "nav.courses": "कोर्स",
    "nav.programs": "कार्यक्रम",
    "nav.about": "हमारे बारे में",
    "nav.contact": "संपर्क करें",
    "nav.login": "लॉगिन",
    "nav.apply": "अभी आवेदन करें",
    "nav.academics": "शैक्षणिक",
    "nav.tracks": "ट्रैक्स",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "थ्रेट इंटेल",
    "nav.resources": "संसाधन",
    "hero.title": "संप्रभु साइबर सुरक्षा शिक्षा",
    "hero.subtitle": "विश्व स्तरीय संकाय के साथ उत्पादन-ग्रेड बुनियादी ढांचे पर प्रशिक्षण प्राप्त करें",
    "hero.cta": "शुरू करें",
    "resources.title": "संसाधन",
    "resources.subtitle": "हमारी व्यापक गाइड और शोध पत्र डाउनलोड करें",
    "resources.ebooks": "ई-बुक्स",
    "resources.whitepapers": "व्हाइटपेपर",
    "resources.download": "डाउनलोड करें",
    "resources.login_required": "लॉगिन आवश्यक",
    "resources.kyc_required": "KYC आवश्यक",
    "resources.locked": "एक्सेस अनलॉक करें",
    "resources.badge": "ज्ञान केंद्र",
    "resources.all": "सभी संसाधन",
    "resources.premium_title": "प्रीमियम संसाधन अनलॉक करें",
    "resources.premium_desc": "हमारी व्यापक ई-बुक्स और व्हाइटपेपर्स तक पहुंचने के लिए मुफ्त खाता बनाएं।",
    "resources.premium_some_kyc": "प्रीमियम संसाधनों के लिए खाता पंजीकरण आवश्यक है। कुछ संसाधनों के लिए KYC सत्यापन आवश्यक है।",
    "resources.pages": "पृष्ठ",
    "resources.tcpwave_docs": "TCPWave दस्तावेज़ीकरण",
    "resources.tcpwave_docs_desc": "TCPWave DDI प्लेटफ़ॉर्म के लिए संपूर्ण दस्तावेज़ीकरण जिसमें API संदर्भ, परिनियोजन गाइड और सर्वोत्तम प्रथाएं शामिल हैं।",
    "resources.view_docs": "दस्तावेज़ देखें",
    "resources.access": "एक्सेस",
    "resources.cat_ebooks": "ई-बुक्स",
    "resources.cat_ebooks_desc": "साइबर सुरक्षा विषयों, करियर विकास और प्रमाणपत्रों पर व्यापक गाइड।",
    "resources.cat_whitepapers": "व्हाइटपेपर",
    "resources.cat_whitepapers_desc": "DNS सुरक्षा, DDI और एंटरप्राइज आर्किटेक्चर पर गहन तकनीकी पेपर।",
    "resources.cat_cheatsheets": "चीट शीट्स",
    "resources.cat_cheatsheets_desc": "सुरक्षा उपकरण, कमांड और सर्वोत्तम प्रथाओं के लिए त्वरित संदर्भ गाइड।",
    "resources.cat_tools": "उपकरण",
    "resources.cat_tools_desc": "T-SPAN द्वारा विकसित और हमारे संकाय द्वारा अनुशंसित ओपन-सोर्स सुरक्षा उपकरण।",
    "resources.cat_glossary": "शब्दावली",
    "resources.cat_glossary_desc": "साइबर सुरक्षा शब्दों और संक्षिप्त रूपों का व्यापक शब्दकोश।",
    "resources.cat_dns_guide": "DNS सुरक्षा गाइड",
    "resources.cat_dns_guide_desc": "एंटरप्राइज DNS सुरक्षा और खतरे से सुरक्षा के लिए अंतिम गाइड।",
    "common.loading": "लोड हो रहा है...",
    "common.learn_more": "और जानें",
    "common.view_all": "सभी देखें",
    "common.submit": "जमा करें",
    "common.cancel": "रद्द करें",
    "footer.copyright": "सर्वाधिकार सुरक्षित",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "सेवा की शर्तें",
  },
  te: {
    "nav.home": "హోమ్",
    "nav.courses": "కోర్సులు",
    "nav.programs": "ప్రోగ్రామ్‌లు",
    "nav.about": "మా గురించి",
    "nav.contact": "సంప్రదించండి",
    "nav.login": "లాగిన్",
    "nav.apply": "ఇప్పుడే దరఖాస్తు చేయండి",
    "nav.academics": "విద్యా సంబంధిత",
    "nav.tracks": "ట్రాక్స్",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "థ్రెట్ ఇంటెల్",
    "nav.resources": "వనరులు",
    "hero.title": "సార్వభౌమ సైబర్ భద్రతా విద్య",
    "hero.subtitle": "ప్రపంచ స్థాయి అధ్యాపకులతో ఉత్పత్తి-గ్రేడ్ మౌలిక సదుపాయాలపై శిక్షణ పొందండి",
    "hero.cta": "ప్రారంభించండి",
    "resources.title": "వనరులు",
    "resources.subtitle": "మా సమగ్ర గైడ్‌లు మరియు పరిశోధనా పత్రాలను డౌన్‌లోడ్ చేయండి",
    "resources.ebooks": "ఈ-బుక్స్",
    "resources.whitepapers": "వైట్‌పేపర్లు",
    "resources.download": "డౌన్‌లోడ్",
    "resources.login_required": "లాగిన్ అవసరం",
    "resources.kyc_required": "KYC అవసరం",
    "resources.locked": "యాక్సెస్ అన్‌లాక్ చేయండి",
    "resources.badge": "నాలెడ్జ్ హబ్",
    "resources.all": "అన్ని వనరులు",
    "resources.premium_title": "ప్రీమియం వనరులను అన్‌లాక్ చేయండి",
    "resources.premium_desc": "మా సమగ్ర ఈ-బుక్స్ మరియు వైట్‌పేపర్లను యాక్సెస్ చేయడానికి ఉచిత ఖాతాను సృష్టించండి.",
    "resources.premium_some_kyc": "ప్రీమియం వనరులకు ఖాతా నమోదు అవసరం. కొన్ని వనరులకు KYC ధృవీకరణ అవసరం.",
    "resources.pages": "పేజీలు",
    "resources.tcpwave_docs": "TCPWave డాక్యుమెంటేషన్",
    "resources.tcpwave_docs_desc": "API రిఫరెన్స్, డిప్లాయ్‌మెంట్ గైడ్‌లు మరియు బెస్ట్ ప్రాక్టీసెస్‌తో సహా TCPWave DDI ప్లాట్‌ఫారమ్ కోసం పూర్తి డాక్యుమెంటేషన్.",
    "resources.view_docs": "డాక్యుమెంటేషన్ చూడండి",
    "resources.access": "యాక్సెస్",
    "resources.cat_ebooks": "ఈ-బుక్స్",
    "resources.cat_ebooks_desc": "సైబర్ భద్రత అంశాలు, వృత్తి అభివృద్ధి మరియు సర్టిఫికేషన్లపై సమగ్ర గైడ్‌లు.",
    "resources.cat_whitepapers": "వైట్‌పేపర్లు",
    "resources.cat_whitepapers_desc": "DNS భద్రత, DDI మరియు ఎంటర్‌ప్రైజ్ ఆర్కిటెక్చర్‌పై లోతైన సాంకేతిక పత్రాలు.",
    "resources.cat_cheatsheets": "చీట్ షీట్లు",
    "resources.cat_cheatsheets_desc": "భద్రతా సాధనాలు, ఆదేశాలు మరియు ఉత్తమ పద్ధతులకు త్వరిత సూచన గైడ్‌లు.",
    "resources.cat_tools": "సాధనాలు",
    "resources.cat_tools_desc": "T-SPAN అభివృద్ధి చేసిన మరియు మా అధ్యాపకులు సిఫార్సు చేసిన ఓపెన్-సోర్స్ భద్రతా సాధనాలు.",
    "resources.cat_glossary": "పదకోశం",
    "resources.cat_glossary_desc": "సైబర్ భద్రత పదాలు మరియు సంక్షిప్తాల సమగ్ర నిఘంటువు.",
    "resources.cat_dns_guide": "DNS భద్రత గైడ్",
    "resources.cat_dns_guide_desc": "ఎంటర్‌ప్రైజ్ DNS భద్రత మరియు ముప్పు రక్షణ కోసం అంతిమ గైడ్.",
    "common.loading": "లోడ్ అవుతోంది...",
    "common.learn_more": "మరింత తెలుసుకోండి",
    "common.view_all": "అన్నీ చూడండి",
    "common.submit": "సమర్పించండి",
    "common.cancel": "రద్దు చేయండి",
    "footer.copyright": "సర్వహక్కులు రిజర్వ్ చేయబడ్డాయి",
    "footer.privacy": "గోప్యతా విధానం",
    "footer.terms": "సేవా నిబంధనలు",
  },
  zh: {
    "nav.home": "首页",
    "nav.courses": "课程",
    "nav.programs": "项目",
    "nav.about": "关于我们",
    "nav.contact": "联系我们",
    "nav.login": "登录",
    "nav.apply": "立即申请",
    "nav.academics": "学术",
    "nav.tracks": "培训轨道",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "威胁情报",
    "nav.resources": "资源",
    "hero.title": "主权网络安全教育",
    "hero.subtitle": "与世界级师资一起在生产级基础设施上进行培训",
    "hero.cta": "开始使用",
    "resources.title": "资源",
    "resources.subtitle": "下载我们的综合指南和研究论文",
    "resources.ebooks": "电子书",
    "resources.whitepapers": "白皮书",
    "resources.download": "下载",
    "resources.login_required": "需要登录",
    "resources.kyc_required": "需要KYC",
    "resources.locked": "解锁访问",
    "resources.badge": "知识中心",
    "resources.all": "所有资源",
    "resources.premium_title": "解锁高级资源",
    "resources.premium_desc": "创建免费账户以访问我们的综合电子书和白皮书。",
    "resources.premium_some_kyc": "高级资源需要账户注册。部分资源需要KYC验证。",
    "resources.pages": "页",
    "resources.tcpwave_docs": "TCPWave 文档",
    "resources.tcpwave_docs_desc": "TCPWave DDI平台的完整文档，包括API参考、部署指南和最佳实践。",
    "resources.view_docs": "查看文档",
    "resources.access": "访问",
    "resources.cat_ebooks": "电子书",
    "resources.cat_ebooks_desc": "关于网络安全主题、职业发展和认证的综合指南。",
    "resources.cat_whitepapers": "白皮书",
    "resources.cat_whitepapers_desc": "关于DNS安全、DDI和企业架构的深入技术论文。",
    "resources.cat_cheatsheets": "速查表",
    "resources.cat_cheatsheets_desc": "安全工具、命令和最佳实践的快速参考指南。",
    "resources.cat_tools": "工具",
    "resources.cat_tools_desc": "T-SPAN开发并由我们的教师推荐的开源安全工具。",
    "resources.cat_glossary": "术语表",
    "resources.cat_glossary_desc": "网络安全术语和缩略语的综合词典。",
    "resources.cat_dns_guide": "DNS安全指南",
    "resources.cat_dns_guide_desc": "企业DNS安全和威胁防护的终极指南。",
    "common.loading": "加载中...",
    "common.learn_more": "了解更多",
    "common.view_all": "查看全部",
    "common.submit": "提交",
    "common.cancel": "取消",
    "footer.copyright": "版权所有",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.courses": "الدورات",
    "nav.programs": "البرامج",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.login": "تسجيل الدخول",
    "nav.apply": "قدم الآن",
    "nav.academics": "الأكاديمية",
    "nav.tracks": "المسارات",
    "nav.tcpwave": "TCPWave",
    "nav.threat_intel": "استخبارات التهديد",
    "nav.resources": "الموارد",
    "hero.title": "تعليم الأمن السيبراني السيادي",
    "hero.subtitle": "تدرب على البنية التحتية الإنتاجية مع أعضاء هيئة التدريس من الطراز العالمي",
    "hero.cta": "ابدأ الآن",
    "resources.title": "الموارد",
    "resources.subtitle": "قم بتنزيل أدلتنا الشاملة وأوراق البحث",
    "resources.ebooks": "الكتب الإلكترونية",
    "resources.whitepapers": "الأوراق البيضاء",
    "resources.download": "تحميل",
    "resources.login_required": "تسجيل الدخول مطلوب",
    "resources.kyc_required": "KYC مطلوب",
    "resources.locked": "فتح الوصول",
    "resources.badge": "مركز المعرفة",
    "resources.all": "جميع الموارد",
    "resources.premium_title": "افتح الموارد المميزة",
    "resources.premium_desc": "أنشئ حسابًا مجانيًا للوصول إلى كتبنا الإلكترونية والأوراق البيضاء الشاملة.",
    "resources.premium_some_kyc": "الموارد المميزة تتطلب تسجيل الحساب. بعض الموارد تتطلب التحقق من KYC.",
    "resources.pages": "صفحات",
    "resources.tcpwave_docs": "وثائق TCPWave",
    "resources.tcpwave_docs_desc": "الوثائق الكاملة لمنصة TCPWave DDI بما في ذلك مرجع API وأدلة النشر وأفضل الممارسات.",
    "resources.view_docs": "عرض الوثائق",
    "resources.access": "الوصول",
    "resources.cat_ebooks": "الكتب الإلكترونية",
    "resources.cat_ebooks_desc": "أدلة شاملة حول موضوعات الأمن السيبراني والتطوير المهني والشهادات.",
    "resources.cat_whitepapers": "الأوراق البيضاء",
    "resources.cat_whitepapers_desc": "أوراق تقنية متعمقة حول أمان DNS وDDI وهندسة المؤسسات.",
    "resources.cat_cheatsheets": "أوراق مرجعية",
    "resources.cat_cheatsheets_desc": "أدلة مرجعية سريعة لأدوات الأمان والأوامر وأفضل الممارسات.",
    "resources.cat_tools": "أدوات",
    "resources.cat_tools_desc": "أدوات أمان مفتوحة المصدر تم تطويرها بواسطة T-SPAN وأوصى بها أعضاء هيئة التدريس لدينا.",
    "resources.cat_glossary": "قاموس المصطلحات",
    "resources.cat_glossary_desc": "قاموس شامل لمصطلحات واختصارات الأمن السيبراني.",
    "resources.cat_dns_guide": "دليل أمان DNS",
    "resources.cat_dns_guide_desc": "الدليل النهائي لأمان DNS للمؤسسات والحماية من التهديدات.",
    "common.loading": "جاري التحميل...",
    "common.learn_more": "اعرف المزيد",
    "common.view_all": "عرض الكل",
    "common.submit": "إرسال",
    "common.cancel": "إلغاء",
    "footer.copyright": "جميع الحقوق محفوظة",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("tspan-language");
      if (saved && Object.keys(translations).includes(saved)) {
        return saved as Language;
      }
    }
    return "en";
  });

  const isRTL = language === "ar";

  useEffect(() => {
    localStorage.setItem("tspan-language", language);
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
