import { FileText, Printer, Sparkles, ShieldCheck, TrendingUp, Calendar, Rocket } from "lucide-react";
import { PageShell } from "@/components/raiffeisen/PageShell";
import { SectionTitle } from "@/components/raiffeisen/primitives";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { executiveBriefData as b } from "@/lib/raiffeisen-mock-data";

export default function ExecutiveBriefPage() {
  return (
    <PageShell>
      <SectionTitle
        eyebrow="Executive brief"
        title="One page. Board-ready. Evidence-linked."
        description="Generated by the Executive Brief Agent from the latest Command Center and Digital Twin state."
        action={
          <Button onClick={() => window.print()} className="bg-neutral-900 text-white hover:bg-neutral-800" data-testid="print-brief">
            <Printer className="mr-2 h-4 w-4" /> Print / Save PDF
          </Button>
        }
      />

      <div className="rounded-2xl border border-neutral-200 bg-white p-8 shadow-sm print:shadow-none">
        <div className="flex items-start justify-between border-b border-neutral-200 pb-4">
          <div>
            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-amber-600">
              Raiffeisenlandesbank Niederösterreich-Wien AG · Real Estate Finance
            </div>
            <h1 className="mt-1 text-3xl font-semibold tracking-tight text-neutral-900">{b.title}</h1>
            <p className="mt-1 max-w-3xl text-sm text-neutral-600">{b.subtitle}</p>
          </div>
          <Badge variant="outline" className="border-amber-300 bg-amber-50 text-amber-800">
            <FileText className="mr-1 h-3 w-3" /> Concept brief · synthetic data
          </Badge>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-3">
          <Section title="Why now" icon={<Sparkles className="h-4 w-4" />}>
            <ul className="space-y-2 text-sm text-neutral-700">
              {b.whyNow.map((w, i) => (
                <li key={i} className="flex gap-2">
                  <span className="mt-2 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500" />
                  <span>{w}</span>
                </li>
              ))}
            </ul>
          </Section>

          <Section title="Risk & governance" icon={<ShieldCheck className="h-4 w-4" />}>
            <ul className="space-y-2 text-sm text-neutral-700">
              {b.riskGovernance.map((w, i) => (
                <li key={i} className="flex gap-2">
                  <span className="mt-2 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                  <span>{w}</span>
                </li>
              ))}
            </ul>
          </Section>

          <Section title="Max V. Zechmann · use case" icon={<TrendingUp className="h-4 w-4" />}>
            <ol className="space-y-2 text-sm text-neutral-700">
              {b.useCase.map((w, i) => (
                <li key={i} className="flex gap-2">
                  <span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-neutral-900 text-[10px] font-bold text-amber-300">
                    {i + 1}
                  </span>
                  <span>{w}</span>
                </li>
              ))}
            </ol>
          </Section>
        </div>

        <SectionTitle eyebrow="Business impact" title="Modelled outcomes (24-month horizon)" />
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {b.businessImpact.map((m) => (
            <div key={m.metric} className="rounded-xl border border-neutral-200 p-4">
              <div className="text-[10px] font-semibold uppercase tracking-wider text-neutral-500">{m.metric}</div>
              <div className="mt-1 text-2xl font-semibold text-neutral-900">{m.value}</div>
              <div className="text-[11px] text-neutral-500">{m.note}</div>
            </div>
          ))}
        </div>

        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          <Card className="border-0 ring-1 ring-neutral-200">
            <CardHeader className="pb-2">
              <CardTitle className="flex items-center gap-2 text-sm">
                <Rocket className="h-4 w-4 text-amber-600" /> 90-day pilot
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {b.pilot90Day.map((s) => (
                <div key={s.week} className="flex items-start gap-3 text-sm">
                  <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[11px] font-semibold text-amber-800 ring-1 ring-amber-200">
                    {s.week}
                  </span>
                  <span className="text-neutral-700">{s.milestone}</span>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="border-0 ring-1 ring-neutral-200">
            <CardHeader className="pb-2">
              <CardTitle className="flex items-center gap-2 text-sm">
                <Calendar className="h-4 w-4 text-neutral-700" /> Suggested meeting agenda
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {b.agenda.map((a) => (
                <div key={a.time} className="flex items-start gap-3 text-sm">
                  <span className="rounded-full bg-neutral-100 px-2 py-0.5 text-[11px] font-semibold text-neutral-800">
                    {a.time}
                  </span>
                  <span className="text-neutral-700">{a.item}</span>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          <Card className="border-0 ring-1 ring-neutral-200">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm">Vercel demo readiness</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-1.5 text-sm text-neutral-700">
                {b.vercelReadiness.map((v, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="mt-2 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500" />
                    <span>{v}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          <Card className="border-0 ring-1 ring-neutral-200">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm">Secure production path</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-1.5 text-sm text-neutral-700">
                {b.productionPath.map((v, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="mt-2 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                    <span>{v}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>

        <div className="mt-10 border-t border-neutral-200 pt-4 text-[11px] text-neutral-500">
          Prepared for Max V. Zechmann — Key Account Manager, Real Estate Finance. Concept demonstration prepared
          for strategic discussion. Uses synthetic data only.
        </div>
      </div>
    </PageShell>
  );
}

function Section({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-neutral-200 p-4">
      <div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-wider text-amber-700">
        {icon}
        {title}
      </div>
      {children}
    </div>
  );
}
